export default Object.freeze({
    ADD_TO_GAME: 'ADD_TO_GAME',
    GAME_OVER: 'GAME_OVER',
    ADD_GAME_RESULTS: 'ADD_GAME_RESULTS',
    RESET_RESULTS: 'RESET_RESULTS',
    SORT_GAME_RESULTS: 'SORT_GAME_RESULTS'
})
